when@prod:
    parameters:
        env(SENTRY_DSN): 'https://c70286fb157048be9ebc6e918e8c2b79@o200403.ingest.sentry.io/1323198'
    sentry:
        dsn: '%env(SENTRY_DSN)%'
        options:
            before_send: 'App\Service\SentryBeforeSend'
            send_default_pii: true
            traces_sampler: 'sentry.callback.traces_sampler'
            integrations:
                - 'Sentry\Integration\IgnoreErrorsIntegration'
        # this hooks into critical paths of the framework (and vendors) to perform
        # automatic instrumentation (there might be some performance penalty)
        # https://docs.sentry.io/platforms/php/guides/symfony/performance/instrumentation/automatic-instrumentation/
        tracing:
            enabled: true

    services:
        Sentry\Integration\IgnoreErrorsIntegration:
            arguments:
                $options:
                    ignore_exceptions:
                        - Symfony\Component\Security\Core\Exception\AccessDeniedException
                        - Symfony\Component\HttpKernel\Exception\NotFoundHttpException
                        - Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException

#        If you are using Monolog, you also need this additional configuration to log the errors correctly:
#        https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
#        register_error_listener: false
#        register_error_handler: false

#    monolog:
#        handlers:
#            sentry:
#                type: sentry
#                level: !php/const Monolog\Logger::ERROR
#                hub_id: Sentry\State\HubInterface

#    Uncomment these lines to register a log message processor that resolves PSR-3 placeholders
#    https://docs.sentry.io/platforms/php/guides/symfony/#monolog-integration
#    services:
#        Monolog\Processor\PsrLogMessageProcessor:
#            tags: { name: monolog.processor, handler: sentry }
